spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  data:
    rest:
      basePath: /api/v1
      enable-enum-translation: true
  jackson:
    mapper:
      infer-property-mutators: false

jwt:
  route:
    auth: /auth
    refresh: /refresh
  header: Authorization
  secret: k@47jdkoKfdI$#(LLdk
  expiration: 604800